import React from 'react'
import './AppContent.css'

export const AppContent = () => {
  return (
    /* CONTENIDO DE LA APLICACIÓN */
        <div className='AppContent'>
            <div className='ContentBox'>
                <h1>Sobre Nosotros</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
            </div>
            <div className='ContentBox'>
                <h1>Contacto</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
            </div>
            <div className='ContentBox'>
                <h1>Proyectos</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
            </div>
            <div className='ContentBox'>
                <h1>Nuestros Clientes</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi sunt saepe officiis nisi ullam architecto laboriosam molestiae temporibus consequatur doloremque iure blanditiis voluptas eos, quasi quisquam perspiciatis esse harum ratione. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt unde exercitationem assumenda voluptatibus sint perferendis, perspiciatis iusto corporis aperiam suscipit, odio nihil vel, qui voluptatem ad laudantium in minus saepe. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum repellat quibusdam dicta ad quos quod quia ex veritatis architecto molestiae neque, similique, provident quo distinctio blanditiis, omnis minus accusantium deleniti.</p>
            </div>
        </div>
  )
}
